about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

posts/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('new/', views.new_post, name='new_post'),
    path('group/<slug>/', views.group_posts, name='group'),
    path(
        'follow/',
        views.follow_index,
        name='follow_index'
    ),
    path('<str:username>/', views.profile, name='profile'),
    path('<str:username>/<int:post_id>/', views.post_view, name='post'),
    path(
        '<str:username>/<int:post_id>/edit/',
        views.post_edit,
        name='post_edit'
    ),
    path(
        '<username>/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path(
        '<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        '<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
    path('', views.index, name='index'),
]

yatube/urls.py
from django.conf import settings
from django.conf.urls import handler404, handler500
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('about/', include('about.urls', namespace='about')),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('adm/', admin.site.urls),
    path('', include('posts.urls')),
]

handler404 = "posts.views.page_not_found"
handler500 = "posts.views.server_error"

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT
    )

posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    title = models.CharField(
        verbose_name='Имя группы',
        help_text='Дайте имя группе',
        max_length=200
    )
    slug = models.SlugField(
        unique=True,
        verbose_name='Ссылка для группы',
        help_text='Задайте ссылку',
    )
    description = models.TextField(
        verbose_name='Описание группы',
        help_text='Опишите сообщество'
    )

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(
        verbose_name='Текс нового поста',
        help_text='Введите текст своей записи'
    )
    pub_date = models.DateTimeField(
        'date published',
        auto_now_add=True
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор поста',
        help_text='Авторство присваивается автоматически'
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name='posts',
        verbose_name='Группа поста',
        help_text='Выберите группу для поста'
    )
    image = models.ImageField(upload_to='posts/', blank=True, null=True)

    class Meta:
        ordering = ['-pub_date']

    def __str__(self):
        return self.text[:15]


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Комментируемая запись',
        help_text='Прокомментируйте запись'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор комментария',
        help_text='Авторство присваивается автоматически'
    )
    text = models.TextField(
        verbose_name='Текс комментария',
        help_text='Введите текст комментария'
    )
    created = models.DateTimeField(
        'date created',
        auto_now_add=True
    )

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return self.text[:10]


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
    )

    class Meta:
        constraints = [models.UniqueConstraint(
            fields=['user', 'author'],
            name='unique follow')]

    def __str__(self):
        return f'{self.author.username}:{self.user.username}'

posts/forms.py
from django import forms

from .models import Comment, Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('group', 'text', 'image')
        labels = {
            'group': 'Сообщество',
            'text': 'Текст записи',
        }
        help_texts = {
            'group': 'Выберите сообщество',
            'text': 'Введите о чем хотите написать',
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

posts/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render

from yatube.settings import COMMENT_PER_PAGE, PAGINATOR

from .forms import CommentForm, PostForm
from .models import Follow, Group, Post

User = get_user_model()


def index(request):
    post_list = Post.objects.all()
    paginator = Paginator(post_list, PAGINATOR)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    return render(
        request,
        'index.html',
        {'page': page}
    )


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()
    paginator = Paginator(posts, PAGINATOR)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    return render(request, 'group.html', {'group': group, 'page': page})


@login_required
def new_post(request):
    form = PostForm(request.POST or None, files=request.FILES or None,)
    if form.is_valid():
        form.instance.author = request.user
        form.save()
        return redirect('index')

    return render(request, 'new_post.html', {'form': form})


def profile(request, username):
    author = get_object_or_404(User, username=username)
    posts = author.posts.all()
    following = request.user.is_authenticated and Follow.objects.filter(
        author=author,
        user=request.user).exists()
    paginator = Paginator(posts, PAGINATOR)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    return render(
        request,
        'profile.html',
        {'author': author, 'page': page, 'following': following}
    )


def post_view(request, username, post_id):
    post = get_object_or_404(Post, id=post_id, author__username=username)
    comments = post.comments.all()
    form = CommentForm()
    paginator = Paginator(comments, COMMENT_PER_PAGE)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    return render(
        request,
        'view_post.html',
        {
            'author': post.author,
            'post': post,
            'page': page,
            'comments': comments,
            'form': form
        }
    )


@login_required
def post_edit(request, username, post_id):
    post = get_object_or_404(Post, id=post_id, author__username=username)
    if post.author != request.user:
        return redirect('post', username, post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if form.is_valid():
        form.save()
        return redirect('post', username, post_id)
    return render(request, 'new_post.html', {'form': form, 'post': post})


@login_required
def add_comment(request, username, post_id):
    post = get_object_or_404(Post, id=post_id, author__username=username)
    form = CommentForm(request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('post', username, post_id)


def page_not_found(request, exception):
    return render(
        request,
        "misc/404.html",
        {"path": request.path},
        status=404
    )


def server_error(request):
    return render(request, "misc/500.html", status=500)


@login_required
def follow_index(request):
    post_list = Post.objects.filter(author__following__user=request.user)
    paginator = Paginator(post_list, PAGINATOR)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    return render(request, "follow.html", {'page': page})


@login_required
def profile_follow(request, username):
    author = User.objects.get(username=username)
    if request.user == author:
        return redirect('profile', username)
    if not Follow.objects.filter(user=request.user, author=author).exists():
        Follow.objects.create(user=request.user, author=author)
    return redirect('profile', username)


@login_required
def profile_unfollow(request, username):
    author = User.objects.get(username=username)
    follow = Follow.objects.filter(user=request.user, author=author)
    if follow.exists():
        follow.delete()
    return redirect('profile', username)

templates/includes/author_card.html
<div class="col-md-3 mb-3 mt-1">
    <div class="card">
            <div class="card-body">
                    <div class="h2">
                        <!-- Имя автора -->
                        {{ author.get_full_name }}
                    </div>
                    <div class="h3 text-muted">
                         <!-- username автора -->
                        @{{ author.get_username }}
                    </div>
            </div>
            <ul class="list-group list-group-flush">
                    <li class="list-group-item">
                            <div class="h6 text-muted">
                            Подписчиков: {{ author.following.count }} <br />
                            Подписан: {{ author.follower.count }}
                            </div>
                    </li>
                    <li class="list-group-item">
                            <div class="h6 text-muted">
                                <!-- Количество записей -->
                                Записей: {{ author.posts.count }}
                            </div>
                    </li>
                    {% if author != request.user and is_profile %} 
                    <li class="list-group-item">
                        {% if following %}
                        <a class="btn btn-lg btn-light" 
                                href="{% url 'profile_unfollow' author.username %}" role="button"> 
                                Отписаться 
                        </a> 
                        {% else %}
                        <a class="btn btn-lg btn-primary" 
                                href="{% url 'profile_follow' author.username %}" role="button">
                        Подписаться 
                        </a>
                        {% endif %}
                    </li> 
                    {% endif %}
            </ul>
    </div>
</div>

templates/includes/card.html
<div class="col-md-3 mb-3 mt-1">
    <div class="card">
            <div class="card-body">
                    <div class="h2">
                        <!-- Имя автора -->
                        {{ author.get_full_name }}
                    </div>
                    <div class="h3 text-muted">
                         <!-- username автора -->
                        @{{ author.get_username }}
                    </div>
            </div>
            <ul class="list-group list-group-flush">
                    <li class="list-group-item">
                            <div class="h6 text-muted">
                            Подписчиков: {{ author.following.count }} <br />
                            Подписан: {{ author.follower.count }}
                            </div>
                    </li>
                    <li class="list-group-item">
                            <div class="h6 text-muted">
                                <!-- Количество записей -->
                                Записей: {{ author.posts.count }}
                            </div>
                    </li>
                    {% if user.is_authenticated and author != request.user %} 
                    <li class="list-group-item">
                        {% if following %}
                        <a class="btn btn-lg btn-light" 
                                href="{% url 'profile_unfollow' author.username %}" role="button"> 
                                Отписаться 
                        </a> 
                        {% else %}
                        <a class="btn btn-lg btn-primary" 
                                href="{% url 'profile_follow' author.username %}" role="button">
                        Подписаться 
                        </a>
                        {% endif %}
                    </li> 
                    {% endif %}
            </ul>
    </div>
</div>

templates/includes/comments.html
{% load user_filters %}

{% if user.is_authenticated %}
<div class="card my-4">
    <form action="{% url 'add_comment' post.author.username post.id %}" method="post">
        {% csrf_token %}
        <h5 class="card-header">Добавить комментарий:</h5>
        <div class="card-body">
            <div class="form-group">
                {{ form.text|addclass:"form-control" }}
            </div>
            <button type="submit" class="btn btn-primary">Отправить</button>
        </div>
    </form>
</div>
{% endif %}

{% for item in page %}
<div class="media card mb-4">
    <div class="media-body card-body">
        <h5 class="mt-0">
            <a href="{% url 'profile' item.author.username %}"
               name="comment_{{ item.id }}">
                {{ item.author.username }}
            </a>
        </h5>
        <p>{{ item.text | linebreaksbr }}</p>
    </div>
</div>
{% endfor %}

templates/includes/footer.html
<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <p class="m-0 text-dark text-center ">
        <a href="{% url 'about:author' %}">Об авторе</a> 
        <a href="{% url 'about:tech' %}">О технологиях</a>
    </p>
    <p class="m-0 text-dark text-center ">Социальная сеть <span style="color:red">Ya</span>tube © {{ year }}, все права защищены. </p>
</footer>

templates/includes/menu.html
{% if user.is_authenticated %} 
<div class="row">
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link {% if index %}active{% endif %}" href="{% url 'index' %}">
                  Все авторы
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link {% if follow %}active{% endif %}" href="{% url 'follow_index' %}">
                Избранные авторы
            </a>
        </li>
    </ul>
</div>
{% endif %}

templates/includes/nav.html
<nav class="navbar navbar-light" style="background-color: #e3f2fd;">
    <a class="navbar-brand" href="/"><span style="color:red">Ya</span>tube</a>
    <nav class="my-2 my-md-0 mr-md-3">
        {% if user.is_authenticated %}
        Пользователь: {{ user.username }}.
        <a class="p-2 text-dark" href="{% url 'new_post' %}">Новая запись</a>
        <a class="p-2 text-dark" href="{% url 'password_change' %}">Изменить пароль</a>
        <a class="p-2 text-dark" href="{% url 'logout' %}">Выйти</a>
        {% else %}
        <a class="p-2 text-dark" href="{% url 'login' %}">Войти</a> |
        <a class="p-2 text-dark" href="{% url 'signup' %}">Регистрация</a>
        {% endif %}
    </nav>
</nav>

templates/includes/paginator.html
{# Отрисовываем навигацию паджинатора только если есть и другие страницы #}
{% if page.has_other_pages %}
<nav>
  <ul class="pagination">
    {% if page.has_previous %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page.previous_page_number }}">&laquo; Предыдущая</a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <span class="page-link">&laquo; Предыдущая</span>
    </li>
    {% endif %}
    {% for i in page.paginator.page_range %}
    {% if page.number == i %}
    <li class="page-item active">
      <span class="page-link">{{ i }}
        <span class="sr-only">(текущая)</span>
      </span>
    </li>
    {% else %}
    <li class="page-item">
      <a class="page-link" href="?page={{ i }}">{{ i }}</a>
    </li>
    {% endif %}
    {% endfor %}
    {% if page.has_next %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page.next_page_number }}">Следующая &raquo;</a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <span class="page-link">Следующая &raquo;</span>
    </li>
    {% endif %}
  </ul>
</nav>
{% endif %}

templates/includes/post.html
<div class="card mb-3 mt-1 shadow-sm">
    {% load thumbnail %}
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img" src="{{ im.url }}">
    {% endthumbnail %}
    <div class="card-body">
            <p class="card-text">
                    <a name="post_{{ post.id }}" href="{% url 'profile' post.author.username %}"><strong class="d-block text-gray-dark">@{{ post.author }}</strong></a>
                    {{ post.text|linebreaksbr }}
            </p>
            {% if post.group %}
            <a class="card-link muted" href="{% url 'group' post.group.slug %}"><strong class="d-block text-gray-dark">#{{ post.group.title }}</strong></a>
            {% endif %}
            <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group ">
                        {% if post.comments.exists %}
                        <div>
                          Комментариев: {{ post.comments.count }} &nbsp;
                        </div>
                        {% endif %}
                            <a class="btn btn-sm btn-primary" href="{% url 'post' post.author.username post.id %}" role="button">
                              Добавить комментарий
                            </a>
                            {% if request.user == post.author %}
                            <a class="btn btn-sm text-muted" href="{% url 'post_edit' post.author.username post.id %}" role="button">Редактировать</a>
                            {% endif %}
                    </div>
                    <small class="text-muted">{{ post.pub_date|date:"d M Y г. H:i" }}</small>
            </div>
    </div>
</div>